'use strict';
const $=s=>document.querySelector(s), KEY='my-reintegration-v1', DRAFT='my-reintegration-draft-v1';
const categories=['Job searching','CV and cover letter preparation','Job applications','Dutch language study','Online training','Networking','Interviews','Other reintegration activities'];
const empty=()=>({version:1,settings:{goal:20,recipient:'',name:''},activities:[],applications:[]});
let state=empty(), storageOK=true, lastRaw=null, view='activities', editing=null, timer;
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const date=s=>new Date(s+'T12:00:00');
const plus=(s,n)=>{let d=date(s);d.setDate(d.getDate()+n);return iso(d)};
const monday=s=>plus(s,-((date(s).getDay()+6)%7));
let selected=iso(new Date()), week=monday(selected);
const fmt=(s,opts={day:'numeric',month:'short',year:'numeric'})=>date(s).toLocaleDateString('en-GB',opts);
const range=()=>`${fmt(week)} – ${fmt(plus(week,6))}`;
const duration=m=>`${Math.floor(m/60)}h ${String(m%60).padStart(2,'0')}m`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(timer);timer=setTimeout(()=>$('#toast').style.display='none',6500)}
function validDate(s){return typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&!isNaN(date(s))&&iso(date(s))===s}
function validate(data){
 if(!data||data.version!==1||!data.settings||!Array.isArray(data.activities)||!Array.isArray(data.applications))throw Error('This is not a supported backup.');
 const st=data.settings;if(!Number.isFinite(st.goal)||st.goal<.25||st.goal>168||typeof st.recipient!=='string'||typeof st.name!=='string'||/[\r\n]/.test(st.recipient))throw Error('Invalid backup settings.');
 const fields={activities:['activity','outcome','category','completed','mail'],applications:['function','company','via','conversation','interview','withWhom','phone','result']};
 for(const kind of Object.keys(fields)){const ids=new Set();for(const r of data[kind]){if(!r||typeof r.id!=='string'||ids.has(r.id)||!validDate(r.date)||fields[kind].some(k=>typeof r[k]!=='string'||r[k].length>50000))throw Error('Invalid or duplicate record in backup.');ids.add(r.id);if(kind==='activities'&&(!r.activity.trim()||!Number.isSafeInteger(r.minutes)||r.minutes<0||r.minutes>10080||!['Yes','No'].includes(r.completed)||!['Yes','No'].includes(r.mail)))throw Error('Invalid activity in backup.');if(kind==='applications'&&(!r.function.trim()||!r.company.trim()||(r.interview&&!validDate(r.interview))))throw Error('Invalid application in backup.');}}
 return JSON.parse(JSON.stringify(data));
}
try{lastRaw=localStorage.getItem(KEY);if(lastRaw)state=validate(JSON.parse(lastRaw));localStorage.setItem('mr-storage-check','1');localStorage.removeItem('mr-storage-check')}catch(e){storageOK=false;setTimeout(()=>toast('Storage could not be opened. Existing data has not been overwritten. Export a backup or restore a valid JSON file.'),100)}
function persist(next){try{if(!storageOK)throw Error('Storage unavailable. Export your data before continuing.');if(localStorage.getItem(KEY)!==lastRaw)throw Error('Data changed in another tab. Reload this tab before saving. Your draft is retained.');const raw=JSON.stringify(next);localStorage.setItem(KEY,raw);lastRaw=raw;state=next;return true}catch(e){toast(e.message);return false}}
function weekRecords(kind){return state[kind].filter(r=>r.date>=week&&r.date<=plus(week,6)).sort((a,b)=>a.date.localeCompare(b.date))}
function render(){const acts=weekRecords('activities'),apps=weekRecords('applications'),minutes=acts.reduce((s,r)=>s+r.minutes,0);$('#weekTitle').textContent=range();$('#jump').value=selected;$('#days').innerHTML=Array.from({length:7},(_,i)=>{const d=plus(week,i),m=acts.filter(r=>r.date===d).reduce((s,r)=>s+r.minutes,0);return `<button class="day ${selected===d?'selected':''} ${iso(new Date())===d?'is-today':''}" aria-pressed="${selected===d}" data-day="${d}" aria-label="${fmt(d)}, ${duration(m)}"><span>${fmt(d,{weekday:'short'})}</span><b>${date(d).getDate()}</b><small>${duration(m)}</small></button>`}).join('');$('#total').textContent=duration(minutes);$('#goalText').textContent=`of ${state.settings.goal}h weekly goal`;$('#progress').value=Math.min(100,minutes/(state.settings.goal*60)*100);$('#progress').setAttribute('aria-label','Weekly goal progress');$('#count').textContent=acts.length;$('#completed').textContent=`${acts.filter(r=>r.completed==='Yes').length} completed`;$('#appCount').textContent=apps.length;
 $('#activityTab').classList.toggle('active',view==='activities');$('#applicationTab').classList.toggle('active',view==='applications');$('#sectionTitle').textContent=view==='activities'?fmt(selected,{weekday:'long',day:'numeric',month:'long'}):'Ongoing applications';$('#sectionHint').textContent=view==='activities'?'Your activities and outcomes for the selected day.':'All applications, across every week. Reports include the selected week only.';$('#add').textContent=view==='activities'?'+ Add activity':'+ Add application';
 const rows=view==='activities'?state.activities.filter(r=>r.date===selected):[...state.applications].sort((a,b)=>b.date.localeCompare(a.date));$('#records').innerHTML=rows.length?rows.map(r=>`<article class="record"><div>${view==='activities'?`<span class="badge ${r.completed==='No'?'pending':''}">${r.completed==='Yes'?'Completed':'In progress'}</span>${r.category?`<span class="badge">${esc(r.category)}</span>`:''}<h3>${esc(r.activity)}</h3><p>${esc(r.outcome||'No outcome recorded yet.')}</p><p class="muted">Mail to Marsha: ${r.mail}</p>`:`<span class="badge">Applied ${fmt(r.date)}</span><h3>${esc(r.function)} · ${esc(r.company)}</h3><p>${esc(r.result||'Awaiting a result')}</p><p class="muted">Via: ${esc(r.via||'—')}<br>Conversation: ${esc(r.conversation||'—')}<br>Interview date: ${r.interview?fmt(r.interview):'—'}<br>With whom: ${esc(r.withWhom||'—')}<br>Contact phone: ${esc(r.phone||'—')}</p>`}</div><div class="record-side">${view==='activities'?`<strong>${duration(r.minutes)}</strong>`:''}<button data-edit="${esc(r.id)}">Edit</button> <button data-delete="${esc(r.id)}">Delete</button></div></article>`).join(''):`<div class="empty"><div class="symbol" aria-hidden="true">＋</div><h3>${view==='activities'?'A little space for your progress.':'Your next opportunity starts here.'}</h3><p>${view==='activities'?'Add an activity to start your record for this day.':'Add an application to keep the details together.'}</p><button id="emptyAdd">${view==='activities'?'Add your first activity':'Add your first application'}</button></div>`;
}
const textField=(name,label,value='',type='text',required=false,wide=false)=>`<label class="${wide?'wide':''}">${label}<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''} maxlength="5000"></label>`;
const area=(name,label,value='',required=false)=>`<label class="wide">${label}<textarea name="${name}" rows="3" maxlength="20000" ${required?'required':''}>${esc(value)}</textarea></label>`;
const select=(name,label,values,value)=>`<label>${label}<select name="${name}">${values.map(v=>`<option ${v===value?'selected':''} value="${esc(v)}">${esc(v||'No category')}</option>`).join('')}</select></label>`;
function openEditor(record=null){editing={kind:view,id:record?.id||null,key:DRAFT+'-'+view+'-'+(record?.id||selected)};let r=record||{date:selected,completed:'No',mail:'No',minutes:0};let draft;try{draft=JSON.parse(localStorage.getItem(editing.key));}catch{}if(draft&&draft.kind===view&&draft.id===editing.id&&confirm('Restore your unfinished draft?'))r=draft.values;
 $('#editTitle').textContent=`${editing.id?'Edit':'Add'} ${view==='activities'?'activity':'application'}`;
 $('#fields').innerHTML=view==='activities'?area('activity','What activity did you do?',r.activity,true)+textField('date','Date',r.date,'date',true)+select('category','Category (optional)',['',...categories,...(r.category&&!categories.includes(r.category)?[r.category]:[])],r.category||'')+area('outcome','What was the result/outcome of this activity for you?',r.outcome)+select('completed','Result (Completed Yes or No)',['No','Yes'],r.completed)+select('mail','Mail to Marsha (Yes or No)',['No','Yes'],r.mail)+`<label>Duration — hours<input name="hours" type="number" min="0" max="168" step="1" required value="${r.hours??Math.floor(r.minutes/60)}"></label><label>Duration — minutes<input name="mins" type="number" min="0" max="59" step="1" required value="${r.mins??r.minutes%60}"></label>`:textField('date','Date of application',r.date,'date',true)+textField('function','Function',r.function,'text',true)+textField('company','Company',r.company,'text',true)+textField('via','Via',r.via)+area('conversation','Conversation',r.conversation)+textField('interview','Interview date',r.interview,'date')+textField('withWhom','With whom (did you speak)',r.withWhom)+textField('phone',"Contact person's phone number",r.phone,'tel',false,true)+area('result','Result (accepted/rejected) and reason',r.result);
 $('#editor').showModal();
}
$('#editForm').addEventListener('input',()=>{try{localStorage.setItem(editing.key,JSON.stringify({...editing,values:Object.fromEntries(new FormData($('#editForm')))}));$('#draftStatus').textContent='Draft saved in this browser.'}catch{$('#draftStatus').textContent='Draft could not be saved. Keep this window open.'}});
$('#editForm').onsubmit=e=>{e.preventDefault();let r=Object.fromEntries(new FormData(e.target));r.id=editing.id||crypto.randomUUID();if(editing.kind==='activities'){r.minutes=Number(r.hours)*60+Number(r.mins);delete r.hours;delete r.mins}const next=structuredClone(state),i=next[editing.kind].findIndex(x=>x.id===r.id);i>=0?next[editing.kind][i]=r:next[editing.kind].push(r);try{validate(next)}catch(err){toast(err.message);return}if(persist(next)){localStorage.removeItem(editing.key);selected=r.date;week=monday(selected);$('#editor').close();render();toast('Record saved.')}};
$('#discard').onclick=()=>{if(confirm('Discard this unfinished draft? Saved records will stay unchanged.')){localStorage.removeItem(editing.key);$('#editor').close()}};
$('#records').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='emptyAdd')return openEditor();if(b.dataset.edit)openEditor(state[view].find(r=>r.id===b.dataset.edit));if(b.dataset.delete&&confirm('Delete this record?')){const next=structuredClone(state);next[view]=next[view].filter(r=>r.id!==b.dataset.delete);if(persist(next)){render();toast('Record deleted.')}}};
$('#days').onclick=e=>{const b=e.target.closest('[data-day]');if(b){selected=b.dataset.day;view='activities';render()}};
$('#prev').onclick=()=>{week=plus(week,-7);selected=plus(selected,-7);render()};$('#next').onclick=()=>{week=plus(week,7);selected=plus(selected,7);render()};$('#today').onclick=()=>{selected=iso(new Date());week=monday(selected);render()};$('#jump').onchange=e=>{if(validDate(e.target.value)){selected=e.target.value;week=monday(selected);render()}};$('#activityTab').onclick=()=>{view='activities';render()};$('#applicationTab').onclick=()=>{view='applications';render()};$('#add').onclick=()=>openEditor();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());
$('#settings').onclick=()=>{for(const k of ['goal','recipient','name'])$('#settingsForm').elements[k].value=state.settings[k];$('#preferences').showModal()};$('#settingsForm').onsubmit=e=>{e.preventDefault();const next=structuredClone(state);next.settings=Object.fromEntries(new FormData(e.target));next.settings.goal=Number(next.settings.goal);if(persist(next)){$('#preferences').close();render();toast('Settings saved.')}};
function download(content,name,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}
const backup=()=>download(JSON.stringify(state,null,2),`my-reintegration-backup-${iso(new Date())}.json`,'application/json');$('#backup').onclick=backup;
$('#import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>10*1024*1024)throw Error('Backup exceeds 10 MB.');const next=validate(JSON.parse(await f.text()));if(confirm(`Replace current data with ${next.activities.length} activities and ${next.applications.length} applications? Your current data will be downloaded first.`)){backup();if(!storageOK){localStorage.setItem(KEY,JSON.stringify(next));lastRaw=localStorage.getItem(KEY);storageOK=true;state=next}else if(!persist(next))return;localStorage.removeItem(DRAFT);render();toast('Backup imported.')}}catch(err){toast('Import failed: '+err.message)}finally{e.target.value=''}};
function reportText(){const acts=weekRecords('activities'),apps=weekRecords('applications');let lines=['WEEKLY RE-INTEGRATION ACTIVITIES REPORT',range(),...(state.settings.name?[state.settings.name]:[]),'','ACTIVITY LOG'];if(!acts.length)lines.push('No activities recorded for this week.');for(const r of acts)lines.push('',fmt(r.date,{weekday:'long',day:'numeric',month:'long',year:'numeric'}),r.activity,...(r.category?['Category: '+r.category]:[]),'Outcome: '+(r.outcome||'Not recorded'),'Completed: '+r.completed,'Duration: '+duration(r.minutes),'Mail to Marsha: '+r.mail);lines.push('','TOTAL TIME: '+duration(acts.reduce((s,r)=>s+r.minutes,0)),'Weekly goal: '+state.settings.goal+' hours','Recorded time includes incomplete activities.','','ONGOING APPLICATIONS — APPLIED THIS WEEK');if(!apps.length)lines.push('No applications recorded for this week.');for(const r of apps)lines.push('',`Date of application: ${fmt(r.date)}`,`Function: ${r.function}`,`Company: ${r.company}`,`Via: ${r.via||'Not recorded'}`,`Conversation: ${r.conversation||'Not recorded'}`,`Interview date: ${r.interview?fmt(r.interview):'Not recorded'}`,`With whom (did you speak): ${r.withWhom||'Not recorded'}`,`Contact person's phone number: ${r.phone||'Not recorded'}`,`Result (accepted/rejected) and reason: ${r.result||'Not recorded'}`);return lines.join('\n')}
$('#report').onclick=()=>{const text=reportText();$('#reportRange').textContent=range();$('#reportText').textContent=text;$('#emailTo').value=state.settings.recipient;$('#emailSubject').value=`Weekly Re-integration Activities Report – ${range()}`;$('#emailBody').value=`Hello,\n\nPlease find below my re-integration activities report for ${range()}.\n\n${text}\n\nPlease let me know if you need any further information.\n\nKind regards,\n${state.settings.name}`;$('#reportDialog').showModal()};
$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(reportText());toast('Report copied.')}catch{const selection=window.getSelection(),r=document.createRange();r.selectNodeContents($('#reportText'));selection.removeAllRanges();selection.addRange(r);toast('Clipboard unavailable. Report selected — copy it manually.')}};
function csvCell(v){let s=String(v??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'}
function csv(){const headers=['Record type','Date','What activity did you do?','Category','What was the result/outcome of this activity for you?','Result (Completed Yes or No)','Duration (hours and minutes)','Duration (minutes)','Mail to Marsha (Yes or No)','Function','Company','Via','Conversation','Interview date','With whom (did you speak)',"Contact person's phone number",'Result (accepted/rejected) and reason'];const rows=[headers,...weekRecords('activities').map(r=>['Activity',r.date,r.activity,r.category,r.outcome,r.completed,duration(r.minutes),r.minutes,r.mail]),...weekRecords('applications').map(r=>['Application',r.date,'','','','','','','',r.function,r.company,r.via,r.conversation,r.interview,r.withWhom,r.phone,r.result])];rows.push(['Weekly total',week,'','','','',duration(weekRecords('activities').reduce((s,r)=>s+r.minutes,0)),weekRecords('activities').reduce((s,r)=>s+r.minutes,0)]);return '\uFEFF'+rows.map(r=>Array.from({length:headers.length},(_,i)=>csvCell(r[i])).join(',')).join('\r\n')}
$('#csv').onclick=()=>download(csv(),`reintegration-${week}.csv`,'text/csv;charset=utf-8');
function emailValues(){const to=$('#emailTo');if(!to.value||!to.checkValidity()||/[\r\n]/.test(to.value)){toast('Enter a valid recipient email address.');to.focus();return null}return{to:to.value,subject:$('#emailSubject').value.replace(/[\r\n]/g,' '),body:$('#emailBody').value}}
$('#email').onclick=()=>{const v=emailValues();if(v)location.href=`mailto:${encodeURIComponent(v.to)}?subject=${encodeURIComponent(v.subject)}&body=${encodeURIComponent(v.body)}`};
$('#eml').onclick=()=>{const v=emailValues();if(!v)return;const b64=s=>btoa(Array.from(new TextEncoder().encode(s),b=>String.fromCharCode(b)).join(''));const body=b64(v.body).match(/.{1,76}/g)?.join('\r\n')||'';download(`To: ${v.to}\r\nSubject: =?UTF-8?B?${b64(v.subject)}?=\r\nX-Unsent: 1\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Transfer-Encoding: base64\r\n\r\n${body}\r\n`,`reintegration-${week}.eml`,'message/rfc822')};
// The PDF contains locally rendered page images. Canvas preserves Unicode without remote fonts.
async function pdf(){const W=1240,H=1754,canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;const ctx=canvas.getContext('2d');ctx.font='24px sans-serif';const lines=[];for(const paragraph of reportText().split('\n')){let line='';for(const ch of paragraph){if(ctx.measureText(line+ch).width>1080){lines.push(line);line=''}line+=ch}lines.push(line)}const images=[];for(let offset=0;offset<lines.length;offset+=43){ctx.fillStyle='#ffffff';ctx.fillRect(0,0,W,H);ctx.fillStyle='#175b4f';ctx.fillRect(80,65,1080,7);ctx.font='24px sans-serif';ctx.fillStyle='#183d38';lines.slice(offset,offset+43).forEach((l,i)=>ctx.fillText(l,80,125+i*34));ctx.font='19px sans-serif';ctx.fillText(`My Reintegration  |  ${range()}  |  Page ${images.length+1}`,80,1680);images.push(Uint8Array.from(atob(canvas.toDataURL('image/jpeg',.94).split(',')[1]),c=>c.charCodeAt(0)))}const enc=new TextEncoder(),chunks=[],offsets=[0];let pos=0;const push=x=>{const b=typeof x==='string'?enc.encode(x):x;chunks.push(b);pos+=b.length};push('%PDF-1.4\n');const obj=(n,parts)=>{offsets[n]=pos;push(`${n} 0 obj\n`);parts.forEach(push);push('\nendobj\n')};obj(1,['<< /Type /Catalog /Pages 2 0 R >>']);obj(2,[`<< /Type /Pages /Count ${images.length} /Kids [${images.map((_,i)=>`${3+i*3} 0 R`).join(' ')}] >>`]);images.forEach((bytes,i)=>{let n=3+i*3;obj(n,[`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] /Resources << /XObject << /Im${i} ${n+1} 0 R >> >> /Contents ${n+2} 0 R >>`]);obj(n+1,[`<< /Type /XObject /Subtype /Image /Width ${W} /Height ${H} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${bytes.length} >>\nstream\n`,bytes,'\nendstream']);const stream=`q 595.28 0 0 841.89 0 0 cm /Im${i} Do Q`;obj(n+2,[`<< /Length ${enc.encode(stream).length} >>\nstream\n${stream}\nendstream`])});const start=pos;push(`xref\n0 ${offsets.length}\n0000000000 65535 f \n`);offsets.slice(1).forEach(o=>push(String(o).padStart(10,'0')+' 00000 n \n'));push(`trailer\n<< /Size ${offsets.length} /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`);download(new Blob(chunks),`reintegration-${week}.pdf`,'application/pdf')}
$('#pdf').onclick=()=>pdf().catch(()=>toast('Could not generate PDF. Please copy the report instead.'));
// Optional first-use setup comes from the URL fragment, which is never sent to hosting.
const setup=new URLSearchParams(location.hash.slice(1));if(setup.has('recipient')&&!state.settings.recipient){const recipient=setup.get('recipient');if(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(recipient)){const next=structuredClone(state);next.settings.recipient=recipient;persist(next)}}if(setup.has('recipient'))history.replaceState(null,'',location.pathname+location.search);
window.addEventListener('storage',e=>{if(e.key===KEY)toast('Your records changed in another tab. Reload before editing here.')});render();
