// Synthetic fixtures only. These records never ship with the application.
const {chromium}=require('playwright');
const {PDFDocument}=require('pdf-lib');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
fs.mkdirSync('test-results',{recursive:true});const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true,permissions:['clipboard-read','clipboard-write']});const page=await context.newPage();const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));page.on('dialog',d=>d.accept());const log=[];const ok=s=>{log.push(s);console.log('PASS',s)};
async function close(id){await page.locator(`[data-close="${id}"]`).click()}
async function getDownload(selector,name){const p=page.waitForEvent('download');await page.locator(selector).click();const d=await p;await d.saveAs('test-results/'+name);return fs.readFileSync('test-results/'+name)}
try{
await page.goto('http://127.0.0.1:8765/#recipient=report%40example.invalid');await page.screenshot({path:'test-results/desktop-empty.png',fullPage:true});assert.equal(await page.title(),'My Reintegration');assert.equal(await page.locator('.record').count(),0);assert.equal(await page.evaluate(()=>location.hash),'');ok('Starts empty, local recipient setup, no fragment retained');
await page.locator('#jump').fill('2026-12-31');await page.locator('#jump').dispatchEvent('change');assert.match(await page.locator('#weekTitle').textContent(),/28 Dec 2026.*3 Jan 2027/);await page.locator('#next').click();assert.match(await page.locator('#weekTitle').textContent(),/4 Jan 2027/);await page.locator('#prev').click();await page.locator('[data-day="2027-01-03"]').click();ok('Monday–Sunday calendar, year boundary, previous/next and Sunday selection');
await page.locator('#add').click();await page.locator('[name="activity"]').fill('Synthetic training — café 学习');await page.locator('[name="outcome"]').fill('Practice completed; further work remains.');await page.locator('[name="hours"]').fill('1');await page.locator('[name="mins"]').fill('45');await page.locator('[name="category"]').selectOption('Online training');await close('editor');await page.locator('[data-day="2026-12-28"]').click();await page.locator('[data-day="2027-01-03"]').click();await page.locator('#add').click();assert.match(await page.locator('[name="activity"]').inputValue(),/Synthetic training/);await page.reload();await page.locator('#jump').fill('2027-01-03');await page.locator('#jump').dispatchEvent('change');await page.locator('#add').click();assert.equal(await page.locator('[name="mins"]').inputValue(),'45');await page.locator('#editForm button[type="submit"]').click();assert.equal(await page.locator('#total').textContent(),'1h 45m');ok('Unfinished draft survives day navigation and reload; incomplete duration counts');
await page.locator('#add').click();await page.locator('[name="activity"]').fill('=Synthetic formula-safe test');await page.locator('[name="hours"]').fill('0');await page.locator('[name="mins"]').fill('30');await page.locator('[name="completed"]').selectOption('Yes');await page.locator('[name="mail"]').selectOption('Yes');await page.locator('#editForm button[type="submit"]').click();assert.equal(await page.locator('#total').textContent(),'2h 15m');await page.locator('[data-edit]').first().click();await page.locator('[name="mins"]').fill('50');await page.locator('#editForm button[type="submit"]').click();assert.equal(await page.locator('#total').textContent(),'2h 20m');await page.reload();await page.locator('#jump').fill('2027-01-03');await page.locator('#jump').dispatchEvent('change');assert.equal(await page.locator('#total').textContent(),'2h 20m');ok('Multiple activities, editing, integer-minute arithmetic and persisted data');
await page.locator('#add').click();await page.locator('[name="activity"]').fill('Draft to discard');await page.locator('#discard').click();await page.locator('#add').click();assert.equal(await page.locator('[name="activity"]').inputValue(),'');await close('editor');
await page.locator('#applicationTab').click();await page.locator('#emptyAdd').click();for(const [k,v] of Object.entries({function:'Synthetic role',company:'Example Company',via:'Company website',conversation:'Synthetic discussion',interview:'2027-01-05',withWhom:'Example contact',phone:'+31000000000',result:'Pending — follow-up planned'}))await page.locator(`[name="${k}"]`).fill(v);await page.locator('#editForm button[type="submit"]').click();assert.equal(await page.locator('#appCount').textContent(),'1');await page.locator('[data-edit]').click();await page.locator('[name="result"]').fill('Rejected — synthetic test reason');await page.locator('#editForm button[type="submit"]').click();assert.match(await page.locator('#records').textContent(),/Rejected/);await page.locator('#next').click();assert.equal(await page.locator('#appCount').textContent(),'0');assert.equal(await page.locator('.record').count(),1);await page.locator('#prev').click();ok('Application fields, edit, all-week listing and selected-week report filter');
await page.locator('#settings').click();assert.equal(await page.locator('[name="recipient"]').inputValue(),'report@example.invalid');await page.locator('[name="goal"]').fill('12.5');await page.locator('[name="name"]').fill('Example Tester');await page.locator('#settingsForm button[type="submit"]').click();assert.match(await page.locator('#goalText').textContent(),/12.5/);ok('Configurable goal and local recipient');
await page.locator('#report').click();const report=await page.locator('#reportText').textContent();assert.match(report,/2h 20m/);assert.match(report,/Rejected — synthetic test reason/);assert.match(report,/2027/);await page.locator('#copy').click();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),report);const csv=(await getDownload('#csv','report.csv')).toString('utf8');assert.match(csv,/"140"/);assert.match(csv,/'=Synthetic/);assert.match(csv,/Contact person's phone number/);const pdf=await getDownload('#pdf','report.pdf');assert.equal(pdf.subarray(0,8).toString(),'%PDF-1.4');const doc=await PDFDocument.load(pdf);assert.ok(doc.getPageCount()>=1);assert.equal(Math.round(doc.getPage(0).getWidth()),595);const eml=(await getDownload('#eml','report.eml')).toString();assert.match(eml,/To: report@example.invalid/);assert.match(eml,/X-Unsent: 1/);await page.locator('#emailSubject').fill('Edited weekly report');await page.locator('#emailBody').fill('Editable professional report');await getDownload('#eml','edited.eml');assert.match(fs.readFileSync('test-results/edited.eml','utf8'),/RWRpdGVkIHdlZWtseSByZXBvcnQ=/);await page.locator('#email').click();await page.screenshot({path:'test-results/report.png',fullPage:true});await close('reportDialog');ok('Historical report, clipboard, formula-safe CSV, valid A4 PDF and editable email draft');
await page.locator('#settings').click();const backup=(await getDownload('#backup','backup.json')).toString();const parsed=JSON.parse(backup);assert.equal(parsed.activities.length,2);assert.equal(parsed.applications.length,1);await close('preferences');await page.locator('[data-delete]').click();assert.equal(await page.locator('.record').count(),0);await page.locator('#activityTab').click();await page.locator('[data-delete]').first().click();assert.equal(await page.locator('#total').textContent(),'0h 30m');await page.locator('#settings').click();await page.locator('#import').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(backup)});await page.waitForFunction(()=>document.querySelector('#total').textContent==='2h 20m');await page.locator('#import').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":9}')});await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('Import failed'));assert.equal(await page.locator('#total').textContent(),'2h 20m');await close('preferences');ok('Delete both record types, JSON round-trip, rejected invalid backup preserves data');
await page.locator('#today').click();assert.equal(await page.locator('#jump').inputValue(),await page.evaluate(()=>new Date().toLocaleDateString('en-CA')));await page.locator('#jump').fill('2027-01-03');await page.locator('#jump').dispatchEvent('change');await page.screenshot({path:'test-results/desktop-populated.png',fullPage:true});await page.setViewportSize({width:375,height:812});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'test-results/mobile.png',fullPage:true});await page.locator('#add').click();assert.ok(await page.evaluate(()=>document.querySelector('#editor').scrollWidth<=document.querySelector('#editor').clientWidth));await page.screenshot({path:'test-results/mobile-editor.png',fullPage:true});await close('editor');ok('Desktop and 375px mobile layout, no horizontal overflow, usable editor');
// Long reports must paginate and all fields must remain escaped.
await page.locator('[data-edit]').first().click();await page.locator('[name="outcome"]').fill(('<script>synthetic</script> Long outcome for pagination. ').repeat(120));await page.locator('#editForm button[type="submit"]').click();assert.equal(await page.locator('#records script').count(),0);await page.locator('#report').click();const longPDF=await getDownload('#pdf','multipage.pdf');assert.ok((await PDFDocument.load(longPDF)).getPageCount()>1);await close('reportDialog');ok('Long Unicode reports paginate; user content is rendered safely');
const second=await context.newPage();await second.goto('http://127.0.0.1:8765');await page.locator('#add').click();await page.locator('[name="activity"]').fill('Stale-tab draft');await second.locator('#settings').click();await second.locator('[name="goal"]').fill('15');await second.locator('#settingsForm button[type="submit"]').click();await page.locator('#editForm button[type="submit"]').click();assert.equal(await page.locator('#editor').evaluate(d=>d.open),true);assert.match(await page.locator('#toast').textContent(),/another tab/);ok('Stale-tab save is blocked without losing draft');
assert.deepEqual(errors,[]);assert.ok(requests.every(u=>u.startsWith('http://127.0.0.1:8765/')||u.startsWith('mailto:')));ok('No JavaScript errors and no record-data network requests');
fs.writeFileSync('test-results/results.json',JSON.stringify({passed:log,errors},null,2));
}catch(e){await page.screenshot({path:'test-results/failure.png',fullPage:true});fs.writeFileSync('test-results/results.json',JSON.stringify({passed:log,error:e.stack,errors},null,2));throw e}finally{await browser.close()}
})();
